// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlofquefrcartfzsngwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsb2ZxdWVmcmNhcnRmenNuZ3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMTkzNjgsImV4cCI6MjA1MjU5NTM2OH0.D_T23zbO7TMNKRJOKpHoJPlTQzmCrHaxsvUg58l4Z-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);